#!/bin/bash

echo
echo -e "\e[2m**press [Q/q] to quit programme**\e[0m"
echo 
echo
echo -e "\e[90m  **please enter an existing student ID to conduct search**\e[0m"
echo 
echo
echo -e "\e[40;38;5;82m\t\tSEARCH STUDENT DETAILS FORM\e[0m"
echo 
echo
 
loop=y
until [ "$loop" = "n" ]
do
 echo -en "\e[2m	Enter Student ID	:	\e[0m"; read inputcode
 echo -e "\e[94m____________________________________________________________________________\e[0m"
 
 sleep 1
 
 if [[ "$inputcode" =~ ^[Qq]$ ]]; then
 loop=n
 echo
 echo "RETURNING TO MAIN MENU..."
 sleep 2
 clear
 ./menuscript
 exit

 else
 search="$(grep "$inputcode" "student.txt")"
 
 while IFS=: read -r programme id name date number address mail 
  do 
	if [ "$inputcode" == "$id" ];then
	  echo 
 	  echo -e "Student Name\t\t: $name"
 	  echo
 	  echo -e "Contact Number\t\t: $number"
 	  echo
 	  echo -e "Mailing Address\t\t: $address"
 	  echo
 	  echo -e "Email\t\t\t: $mail"
 	  echo
 	  loop=n
 	else
 	  echo
 	  echo -e "\e[31mSTUDENT NOT FOUND. PLEASE TRY AGAIN BY ENTERING A VALID ID. (00XXX00000) \e[0m"
 	  echo
 	fi
  done <<< $search
  
fi
done
 
 until [ "$quit" = "y" ]
 do
  echo
  echo -en "\e[7mSearch Another Student? YES[Y] OR NO[N]\t\e[0m: ";read choice1
  echo
  
   case "$choice1" in
    [Yy])
    	quit=y
    	clear
    	./searchstudentscript
 	exit
    	;;
    [Nn])
    	quit=y
    	echo
    	echo "RETURNING TO MAIN MENU..."
    	echo
    	sleep 2
    	clear
    	./menuscript
    	exit
    	;;
    *)
    	echo -en "\n\e[31mINVALID OPTION.PLEASE TRY AGAIN.\e[0m"
 	echo " "
    	;;
    esac
    done
   echo ""
 done
